'use client';
// Central icon map so components can do <I.bed size={18} /> the same way
// the original prototype did, but backed by real lucide-react icons.
import {
  LayoutGrid, Calendar, Users, FileText, Pill, Heart, CreditCard, AlertTriangle,
  Bell, Search, Mic, Sparkles, BedDouble, Ambulance, FlaskConical, Box, TrendingUp,
  Building2, Stethoscope, Brain, Baby, Bone, ChevronRight, ChevronDown, ArrowLeft,
  Check, Plus, Clock, MapPin, Phone, Download, Share2, QrCode, Settings, ShieldCheck,
  Syringe, Truck, Pencil, Eye, LogOut, Globe, Filter, IndianRupee, Loader2, X, Send,
  MessageCircle, RefreshCw, Smile,
} from 'lucide-react';

export const I = {
  grid: LayoutGrid,
  calendar: Calendar,
  users: Users,
  file: FileText,
  pill: Pill,
  heart: Heart,
  card: CreditCard,
  alert: AlertTriangle,
  bell: Bell,
  search: Search,
  mic: Mic,
  sparkle: Sparkles,
  bed: BedDouble,
  ambulance: Ambulance,
  flask: FlaskConical,
  box: Box,
  trend: TrendingUp,
  building: Building2,
  stethoscope: Stethoscope,
  brain: Brain,
  baby: Baby,
  bone: Bone,
  tooth: Smile,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  arrowLeft: ArrowLeft,
  check: Check,
  plus: Plus,
  clock: Clock,
  mapPin: MapPin,
  phone: Phone,
  download: Download,
  share: Share2,
  qr: QrCode,
  settings: Settings,
  shieldCheck: ShieldCheck,
  syringe: Syringe,
  truck: Truck,
  edit: Pencil,
  eye: Eye,
  logout: LogOut,
  globe: Globe,
  filter: Filter,
  rupee: IndianRupee,
  loader: Loader2,
  close: X,
  send: Send,
  chat: MessageCircle,
  refresh: RefreshCw,
};
